# Generated by Django 2.1 on 2023-05-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='url',
        ),
    ]
